# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcqOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('acq_date', models.CharField(max_length=50)),
                ('experimenter', models.CharField(max_length=250)),
                ('img_method', models.CharField(max_length=250)),
                ('microscope', models.CharField(max_length=250)),
                ('camera', models.CharField(max_length=250)),
                ('scope_website', models.CharField(max_length=2083)),
                ('magnification', models.CharField(max_length=250)),
                ('num_ap', models.CharField(max_length=250)),
                ('rfp_time', models.CharField(max_length=250)),
                ('rfp_power', models.CharField(max_length=250)),
                ('gfp_time', models.CharField(max_length=250)),
                ('gfp_power', models.CharField(max_length=250)),
                ('worm_stage', models.CharField(max_length=250)),
                ('sex', models.CharField(max_length=250)),
                ('strain_genotype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('green_id', models.IntegerField()),
                ('red_id', models.IntegerField()),
                ('merged_id', models.IntegerField(primary_key=True, serialize=False)),
                ('worm_stage', models.CharField(max_length=250)),
                ('orientation', models.CharField(max_length=250)),
                ('img_date', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=250)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageManagement.Acquisition')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=2048)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageManagement.Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'M'), ('female', 'F')], default='F', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.AddField(
            model_name='acqoptional',
            name='id_acq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageManagement.Acquisition'),
        ),
        migrations.AlterUniqueTogether(
            name='imageoptional',
            unique_together=set([('id_image', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='acqoptional',
            unique_together=set([('id_acq', 'key')]),
        ),
    ]
